### ISSUE TITLE
Expo 38 problem RNGetRandomValues.getRandomBase64

### ISSUE THREAD

**Issue by aplinxy9plin** [LinusU/react-native-get-random-values#16]
I use this lib version 1.5.0 SDK:38.0.0 on snack.expo.io and got this throw: Expo managed workflow support for react-native-get-random-values is only available in SDK 39 and higher.

If I use 1.4.0 version of this lib got this error:  [TypeError: null is not an object (evaluating 'RNGetRandomValues.getRandomBase64')]

How can I fixed it? Just wait for 39 expo?... :(

**Comment by LinusU** [comment]
> How can I fixed it? Just wait for 39 expo?

Unfortunately, this is the only way for now 😅
