### ISSUE TITLE
Expo managed workflow support for react-native-get-random-values is only avaiable in SDK 39 and higher.

### ISSUE THREAD

**Issue by Picklemaniac** [LinusU/react-native-get-random-values#18]
Exactly like the title says. This is what I am getting when just importing react-native-get-random-values.

Correct me if I am wrong, but that version doesn't yet exist?

**Comment by ctavan** [comment]
Exactly: Expo SDK will be released within the next few weeks and only then react-native-get-random-values will start working in expo managed workflows.

See https://github.com/LinusU/react-native-get-random-values/pull/13 for details and references.
