### ISSUE TITLE
Question: does it need "expo-random"?

### ISSUE THREAD

**Issue by Hirbod** [LinusU/react-native-get-random-values#21]
Hey @LinusU,

I've seen so many confusing issues, docs and blogs on this topic but one thing I'm still unsure about: do we still have to install "expo-random" in Expo SDK 39 or is it enough to install your library now to polyfill?

**Comment by harshmaur** [comment]
Same question!

**Comment by LinusU** [comment]
Sorry for the late reply! You do _not_ need to install `expo-random`.

If there is anything that could be more clear in the documentation I would love a pull request!

**Comment by Hirbod** [comment]
Yeah, a hint about that fact :)

**Comment by LinusU** [comment]
Looking thru the readme I don't see any mentioning of `expo-random`, what made you think that you had to install it? 🤔

**Comment by harshmaur** [comment]
Yes. I figured. Infact with expo-random it crashed on android. 

Also it should be clearer where to import the module. It should be before everything else in index.js. 


I'll submit a PR

**Comment by Hirbod** [comment]
Looking thru the readme I don't see any mentioning of expo-random, what made you think that you had to install it? 🤔
Coming from EXPO Git and the original Ticket issuing this problem and having a lot of mentions about expo-random :D

At the end, the original expo ticket made me think of it

**Comment by LinusU** [comment]
added a comment in that thread: https://github.com/expo/expo/issues/7209#issuecomment-712229139
