### ISSUE TITLE
How can I link this? 

### ISSUE THREAD

**Issue by thomasMinshull** [LinusU/react-native-get-random-values#24]
I've received the following error 
"[javascript] TypeError: null is not an object (evaluating 'r(d[0]).NativeModules.RNGetRandomValues.getRandomBase64')" 
 
after running `npm install --save react-native-get-random-values` and pod install. Normally at this point I would attempt to add the reference to the `.podspec` in my podfile. This lib doesn't seem to have a podspec file. How can I add this to my podfile?

**Comment by thomasMinshull** [comment]
I was mistaken, there is a podspec I was expecting it to be named RNGetRandomValues.podspec, not react-native-get-random-values.podspec. As a result I over looked it. 

I was able to add the path to the podspec to my Podfile.

**Comment by enricop89** [comment]
@thomasMinshull hey Thomas, how were you able to link this to your podspec? Can you share an example please?

**Comment by LinusU** [comment]
We've added `npx pod-install` to the installation instructions now which should link it for you ☺️
