### ISSUE TITLE
crypto.randomUUID for react native

### ISSUE THREAD

**Issue by markrity** [LinusU/react-native-get-random-values#32]
Hi , 
Right now the implementation using v4 uuid , since Node 14.17.0 there were `crypto.randomUUID` introduced, that is by 3 times faster by benchmarks than v4. 

Any plans on adding `crypto.randomUUID` implementation for this package? 

Thanks :)

**Comment by LinusU** [comment]
💥 https://github.com/LinusU/react-native-random-uuid

**Comment by markrity** [comment]
@LinusU Boom 💥 ! Thank you.
