### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by checklist** [LinusU/react-native-get-random-values#34]
Can you please add Typescript support as currently we use "@types/uuid": "^8.3.3" in devDependencies but it causes:

warn Package @types/uuid has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/userx/project/node_modules/@types/uuid/package.json

Thanks!

**Comment by LinusU** [comment]
This seems to be a problem with either `@types/uuid` or the `uuid` package? I don't see how `react-native-get-random-values` can affect the error you got?
