### ISSUE TITLE
Use expo-crypto  instead expo-random starting from expo 49

### ISSUE THREAD

**Issue by sem4phor** [LinusU/react-native-get-random-values#46]
expo-random is now deprecated in favor of expo-crypto 

See: https://docs.expo.dev/versions/latest/sdk/random/

So to generate random bytes this package propably need to use https://docs.expo.dev/versions/latest/sdk/random/ in the future.

**Comment by LinusU** [comment]
This was already fixed in #45, released as [🚢 1.9.0 / 2023-05-18](https://github.com/LinusU/react-native-get-random-values/releases/tag/v1.9.0)
